import { useCallback, useEffect, useState } from 'react'
import { AlertTriangle, RefreshCw } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import DashboardLayout from '../components/DashboardLayout'
import ResourceAllocationDashboardContent from '../components/ResourceAllocationDashboardContent'
import StatusBadge from '../components/StatusBadge'
import useResponseOperationsDashboard from '../hooks/useResponseOperationsDashboard'
import { getOperationalRequests, getTeams, reviewOperationalRequest } from '../services/responseOperationsService'
import { requirementLabels } from '../utils/responseRequirements'

export default function DistrictResourceDashboard() {
  const navigate = useNavigate(); const dashboard = useResponseOperationsDashboard(true)
  const [requests, setRequests] = useState([]); const [teams, setTeams] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const loadRequests = useCallback(async () => { try { const [nextRequests, nextTeams] = await Promise.all([getOperationalRequests(), getTeams()]); setRequests(nextRequests); setTeams(nextTeams); setError('') } catch (requestError) { setError(requestError.response?.data?.error?.message || 'Unable to load incoming requests.') } }, [])
  useEffect(() => { queueMicrotask(loadRequests) }, [loadRequests])
  const review = async (request, decision) => { let teamId; let rejectionReason; if (decision === 'APPROVE') { const tokens = { RESCUE: ['rescue'], MEDICAL: ['medical'], POLICE: ['police'], ARMED_FORCES: ['army', 'armed'], FIRE_RESCUE: ['fire'] }[request.capability] || []; const suitable = teams.find((team) => team.status === 'AVAILABLE' && Number(team.capacity || 0) >= request.requestedPersonnelCount && tokens.some((token) => `${team.name} ${team.type}`.toLowerCase().includes(token))); if (!suitable) return setError('No suitable available team has sufficient capacity for this request.'); teamId = suitable.id } else { rejectionReason = window.prompt('Rejection reason'); if (!rejectionReason?.trim()) return } setBusy(true); try { await reviewOperationalRequest(request.requestId, { decision, teamId, rejectionReason, reviewedBy: 'District / Resource Coordination Officer' }); await loadRequests() } catch (requestError) { setError(requestError.response?.data?.error?.message || 'Unable to review request.') } finally { setBusy(false) } }
  const pending = requests.filter((request) => request.status === 'PENDING')
  return <DashboardLayout breadcrumb="District Resource Coordination"><div className="content response-operations-page"><header className="response-page-header"><div><p className="warning-eyebrow">District / Resource Coordination Officer</p><h1>District Resource Coordination</h1><p className="subtitle">Review operational requests and coordinate relief-resource fulfilment.</p></div><button className="btn btn-secondary" onClick={() => { loadRequests(); dashboard.retry() }}><RefreshCw size={14}/> Refresh</button></header>{error && <div className="response-partial-warning"><AlertTriangle size={17}/>{error}</div>}<section className="response-panel"><div className="response-panel-heading"><div><h2>Incoming Operational Requests</h2><p>Approval assigns a suitable currently available team but does not deploy it.</p></div><span>{pending.length} pending</span></div>{requests.length === 0 ? <div className="response-inline-state">No operational requests received.</div> : <div className="table-wrap"><table className="response-table"><thead><tr><th>Incident</th><th>Capability</th><th>Personnel</th><th>Location</th><th>Required</th><th>Priority</th><th>Status</th><th>Team / Reason</th><th>Action</th></tr></thead><tbody>{requests.map((request) => <tr key={request.id}><td>{request.incident?.incidentId}</td><td>{requirementLabels[request.capability]}</td><td>{request.requestedPersonnelCount}</td><td>{request.requestedLocation}</td><td>{new Date(request.requiredAt).toLocaleString()}</td><td><StatusBadge value={request.priority}/></td><td><StatusBadge value={request.status}/></td><td>{request.approvedTeam?.name || request.rejectionReason || '—'}</td><td>{request.status === 'PENDING' ? <div><button className="btn response-row-action" disabled={busy} onClick={() => review(request, 'APPROVE')}>Approve</button> <button className="btn cancel-btn" disabled={busy} onClick={() => review(request, 'REJECT')}>Reject</button></div> : 'Reviewed'}</td></tr>)}</tbody></table></div>}</section><ResourceAllocationDashboardContent incidents={dashboard.incidents} assignments={dashboard.assignments} shelters={dashboard.shelters} distributions={dashboard.distributions} inventory={dashboard.inventory} deliveryResources={dashboard.deliveryResources} errors={dashboard.errors}/><button className="btn continue-btn" onClick={() => navigate('/response-operations')}>View Response Operations</button></div></DashboardLayout>
}
