import { ArrowRight, Check, Download, House, MessageSquare, ShieldCheck, Siren, Smartphone, Users } from 'lucide-react';

export default function AreaScreen(props) {
  const { Header, Badge, Button, Field, MapPanel, selectedHazard, warning, navigate, updateWarning, toggleInList, saveDraft, setToast } = props;
  return <><Header title="Affected Area & Warning Message" eyebrow="WARNING WORKFLOW · TARGET & COMPOSE" /><div className="stepper"><div className="step done"><span><Check size={15}/></span>Review hazard</div><i/><div className="step done"><span><Check size={15}/></span>Assess event</div><i/><div className="step done"><span><Check size={15}/></span>Warning level</div><i/><div className="step active"><span>4</span>Affected area</div><i/><div className="step"><span>5</span>Review</div></div><div className="summary-band compact-band"><div><span>Selected hazard ID</span><strong>{selectedHazard.id}</strong></div><div><span>Hazard type</span><strong>{selectedHazard.type}</strong></div><div><span>Warning level</span><Badge tone={warning.level}>{warning.level}</Badge></div><div><span>Current status</span><strong>For warning issuance</strong></div></div>
    <div className="area-grid"><section className="panel area-select"><div className="panel-heading"><div><h2>1. Affected area selection</h2><p>Choose districts and DS divisions</p></div></div><Field label="District"><select value={warning.districts[0] || selectedHazard.district} onChange={(e) => updateWarning('districts', [e.target.value])}>{['Colombo', 'Gampaha', 'Kandy', 'Galle', 'Matara', 'Ratnapura', 'Nuwara Eliya', 'Kalutara', 'Trincomalee', 'Batticaloa'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="DS division"><select defaultValue={selectedHazard.ds}><option>{selectedHazard.ds}</option><option>Kelaniya</option><option>Wattala</option><option>Gampaha</option></select></Field><div className="select-label">Affected areas <small>Select all that apply</small></div><div className="area-checks">{['Gampaha', 'Kelaniya', 'Wattala', 'Negombo', 'Minuwangoda', 'Katana', 'Colombo', 'Kandy', 'Matara', 'Ratnapura'].map((area) => <label key={area}><input type="checkbox" checked={warning.areas.includes(area)} onChange={() => toggleInList('areas', area)} />{area}</label>)}</div><MapPanel compact pins={3}/></section>
      <div className="area-main"><section className="panel citizen-summary"><div className="panel-heading"><div><h2>2. Target citizen summary</h2><p>Estimated audience in selected areas</p></div></div><div className="citizen-stats"><div><Users/><span><b>{(warning.areas.length * 12480).toLocaleString()}</b><small>Estimated population</small></span></div><div><House/><span><b>{(warning.areas.length * 3120).toLocaleString()}</b><small>Households</small></span></div><div><Users/><span><b>{(warning.areas.length * 1846).toLocaleString()}</b><small>Vulnerable residents</small></span></div><div><ShieldCheck/><span><b>12</b><small>Safe zones identified</small></span></div></div></section>
        <section className="panel message-compose"><div className="panel-heading"><div><h2>3. Warning message composer</h2><p>Write clear, actionable public guidance</p></div></div><Field label="Warning title"><input value={warning.title} onChange={(e) => updateWarning('title', e.target.value)} /></Field><Field label="Message content"><textarea rows="4" maxLength="1500" value={warning.message} onChange={(e) => updateWarning('message', e.target.value)} /><small className="char-count">{warning.message.length} / 1500</small></Field><Field label="Safety instructions"><textarea rows="3" maxLength="1000" value={warning.instructions} onChange={(e) => updateWarning('instructions', e.target.value)} /><small className="char-count">{warning.instructions.length} / 1000</small></Field><div className="form-grid two-col"><Field label="Message language"><select value={warning.language} onChange={(e) => updateWarning('language', e.target.value)}>{['English', 'Sinhala', 'Tamil', 'English + Sinhala', 'English + Tamil', 'All three languages'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Message format"><select value={warning.format} onChange={(e) => updateWarning('format', e.target.value)}>{['Text only', 'Text + Map Link', 'Text + Image', 'Rich notification'].map((x) => <option key={x}>{x}</option>)}</select></Field></div></section></div>
      <div className="area-side"><section className="panel channel-panel"><div className="panel-heading"><div><h2>4. Channels</h2><p>Select delivery methods</p></div></div>{[['Push Notification', Smartphone], ['SMS Alert', MessageSquare], ['Audible / Siren', Siren]].map(([label, Icon]) => <label className="channel-option" key={label}><input type="checkbox" checked={warning.channels.includes(label)} onChange={() => toggleInList('channels', label)} /><Icon size={18}/><span>{label}<small>{label === 'Push Notification' ? 'Mobile app and web portal' : label === 'SMS Alert' ? 'Telecom provider delivery' : 'Public warning system'}</small></span></label>)}</section>
        <section className="panel schedule-panel"><div className="panel-heading"><div><h2>5. Validity & schedule</h2><p>Set the warning period</p></div></div><Field label="Start time"><input type="datetime-local" value={warning.start} onChange={(e) => updateWarning('start', e.target.value)} /></Field><Field label="End time"><input type="datetime-local" value={warning.end} onChange={(e) => updateWarning('end', e.target.value)} /></Field><Field label="Expiry (auto-cancel)"><input type="datetime-local" value={warning.expiry} onChange={(e) => updateWarning('expiry', e.target.value)} /></Field></section><section className="panel notes-panel"><div className="panel-heading"><div><h2>6. Officer notes</h2></div></div><textarea rows="4" value={warning.remarks} onChange={(e) => updateWarning('remarks', e.target.value)} /></section></div></div>
    <div className="workflow-actions"><Button onClick={() => navigate('level', 'Assessments')}>Back</Button><div><Button variant="secondary-blue" icon={Download} onClick={saveDraft}>Save draft</Button><Button variant="primary" icon={ArrowRight} onClick={() => { if (!warning.areas.length || !warning.channels.length) { setToast('Select at least one affected area and delivery channel'); return }; navigate('review', 'Warnings') }}>Review & publish</Button></div></div>
  </>;
}
