import { AlertTriangle, ArrowRight, Bell, ChevronLeft, ChevronRight, Clock3, CloudRain, FileText, Filter, Info, Layers3, MapPin, MoreHorizontal, Mountain, Search, Send, Users, Waves } from 'lucide-react';

export default function DashboardScreen(props) {
  const { Header, Badge, Button, MapPanel, hazards, setSelectedHazardId, filter, setFilter, filteredHazards, navigate, beginWarning, setModal, setToast, setPage, page } = props;
  const activeHazardCount = hazards.filter((hazard) => ['Active', 'Monitoring', 'Pending'].includes(hazard.status)).length;
  const pendingWarningCount = props.warnings.filter((warning) => warning.status === 'Published').length;
  const severeHazardCount = hazards.filter((hazard) => hazard.severity === 'High').length;
  const districtCount = new Set(hazards.map((hazard) => hazard.district)).size;
  return <>
    <Header title="Hazard Monitoring Dashboard" actions={<div className="updated"><Clock3 size={17} /><span><b>Last updated</b><small>Today, 10:30 AM</small></span></div>} />
    <div className="stat-grid">
      <div className="stat-card"><span className="stat-icon danger"><AlertTriangle /></span><div><small>Active hazards</small><strong>{activeHazardCount}</strong><p>across {districtCount} districts</p></div><span className="stat-trend">Current records</span></div>
      <div className="stat-card"><span className="stat-icon amber"><Bell /></span><div><small>Published warnings</small><strong>{pendingWarningCount}</strong><p>active records</p></div><span className="stat-trend neutral">Review status</span></div>
      <div className="stat-card"><span className="stat-icon slate"><Users /></span><div><small>Severe incidents</small><strong>{severeHazardCount}</strong><p>high severity</p></div><span className="stat-trend neutral">Current records</span></div>
      <div className="stat-card"><span className="stat-icon teal"><MapPin /></span><div><small>Target districts</small><strong>{districtCount}</strong><p>represented in records</p></div><span className="stat-trend">Current coverage</span></div>
    </div>
    <section className="filter-bar"><div className="search-field"><Search size={17} /><input aria-label="Search hazards" placeholder="Search by ID, type or location..." value={filter.search} onChange={(event) => setFilter({ ...filter, search: event.target.value })} /></div>
      <select aria-label="Filter by hazard type" value={filter.type} onChange={(event) => setFilter({ ...filter, type: event.target.value })}><option>All types</option>{[...new Set(hazards.map((h) => h.type))].map((type) => <option key={type}>{type}</option>)}</select>
      <select aria-label="Filter by district" value={filter.district} onChange={(event) => setFilter({ ...filter, district: event.target.value })}><option>All districts</option>{[...new Set(hazards.map((h) => h.district))].map((district) => <option key={district}>{district}</option>)}</select>
      <select aria-label="Filter by severity" value={filter.severity} onChange={(event) => setFilter({ ...filter, severity: event.target.value })}><option>All severities</option>{['High', 'Medium', 'Low'].map((severity) => <option key={severity}>{severity}</option>)}</select>
      <select aria-label="Filter by status" value={filter.status} onChange={(event) => setFilter({ ...filter, status: event.target.value })}><option>All statuses</option>{['Monitoring', 'Active', 'Warning Issued', 'Pending'].map((status) => <option key={status}>{status}</option>)}</select>
      <button className="filter-icon" aria-label="Clear filters" title="Clear filters" onClick={() => setFilter({ search: '', type: 'All types', district: 'All districts', severity: 'All severities', status: 'All statuses' })}><Filter size={17} /></button>
    </section>
    <div className="dashboard-grid"><section className="panel hazards-panel"><div className="panel-heading"><div><h2>Active hazard events</h2><p>Review and assess current incidents</p></div><button className="text-button" onClick={() => { setFilter({ ...filter, status: 'All statuses' }); setPage(2) }}>View all <ArrowRight size={15} /></button></div>
      <div className="table-wrap"><table><thead><tr><th>Hazard ID</th><th>Hazard type</th><th>District</th><th>Severity</th><th>Status</th><th>Updated</th><th /></tr></thead><tbody>{filteredHazards.slice((page - 1) * 6, page * 6).map((hazard) => <tr key={hazard.id} onClick={() => { setSelectedHazardId(hazard.id); navigate('details', 'Hazard Monitoring') }}><td><button className="link-button" onClick={(event) => { event.stopPropagation(); setSelectedHazardId(hazard.id); navigate('details', 'Hazard Monitoring') }}>{hazard.id}</button></td><td><span className="hazard-type-icon">{hazard.type.toLowerCase().includes('rain') ? <CloudRain size={16} /> : hazard.type.toLowerCase().includes('land') ? <Mountain size={16} /> : <Waves size={16} />}{hazard.type}</span></td><td>{hazard.district}</td><td><Badge>{hazard.severity}</Badge></td><td><Badge>{hazard.status}</Badge></td><td className="muted">{hazard.updated}</td><td><button className="icon-button" aria-label={`Actions for ${hazard.id}`} onClick={(event) => { event.stopPropagation(); setSelectedHazardId(hazard.id); setModal('hazard-actions') }}><MoreHorizontal size={18} /></button></td></tr>)}</tbody></table>
        {filteredHazards.length === 0 && <div className="empty-state">No hazards match these filters. Try adjusting your search.</div>}</div>
      <div className="table-footer"><span>Showing {filteredHazards.length ? (page - 1) * 6 + 1 : 0}–{Math.min(page * 6, filteredHazards.length)} of {filteredHazards.length} hazards</span><div className="pagination"><button aria-label="Previous page" onClick={() => setPage(1)} disabled={page === 1}><ChevronLeft size={16} /></button><button className={page === 1 ? 'current' : ''} onClick={() => setPage(1)}>1</button><button className={page === 2 ? 'current' : ''} onClick={() => setPage(2)}>2</button><button aria-label="Next page" onClick={() => setPage(2)} disabled={page === 2}><ChevronRight size={16} /></button></div></div>
    </section><section className="panel overview-panel"><div className="panel-heading"><div><h2>Hazard overview</h2><p>Incidents across Sri Lanka</p></div><button className="icon-button" aria-label="Map layers" onClick={() => setToast('Map layers updated')}><Layers3 size={17} /></button></div><MapPanel /><div className="map-caption"><span><i className="dot red" /> 3 High risk</span><span><i className="dot orange" /> 4 Moderate</span><button className="text-button" onClick={() => navigate('dashboard', 'Hazard Monitoring')}>Open map <ArrowRight size={14} /></button></div></section></div>
    <section className="notification-strip"><span className="notification-pulse"><Info size={17} /></span><div><b>System notifications</b><span>12 active hazards across 8 districts. 3 new weather station reports received.</span><small><i className="online-dot" /> All services operational <span className="separator">·</span> Communications link secure</small></div><Button variant="danger-button" icon={Send} onClick={() => beginWarning()}>Create warning</Button><Button variant="teal-button" icon={FileText} onClick={() => navigate('warnings', 'Warnings')}>View warnings</Button></section>
  </>;
}
