import { ArrowRight, Check, Download } from 'lucide-react';

export default function AssessmentScreen(props) {
  const { Header, Badge, Button, Field, MapPanel, selectedHazard, navigate, updateHazard, saveDraft, setToast, reportCount, setReportCount, photoCount, setPhotoCount } = props;
  return <><Header title="Create / Update Hazard Event" eyebrow="ASSESSMENT WORKFLOW · EVENT DETAILS" actions={<div className="workflow-tag"><span className="online-dot" /> Draft assessment</div>} /><div className="stepper"><div className="step done"><span><Check size={15}/></span>Review hazard</div><i/><div className="step active"><span>2</span>Assess event</div><i/><div className="step"><span>3</span>Warning level</div><i/><div className="step"><span>4</span>Affected area</div><i/><div className="step"><span>5</span>Review</div></div>
    <div className="summary-band compact-band"><div><span>Hazard ID</span><strong>{selectedHazard.id}</strong></div><div><span>District</span><strong>{selectedHazard.district}</strong></div><div><span>Source</span><strong>{selectedHazard.source}</strong></div><div><span>Record status</span><Badge>Draft</Badge></div></div>
    <div className="assessment-grid"><section className="panel form-panel"><div className="panel-heading"><div><h2>Event details</h2><p>Review and update the incident record</p></div><span className="required-note">* Required fields</span></div><div className="form-grid"><Field label="Hazard type *"><select value={selectedHazard.type} onChange={(e) => updateHazard('type', e.target.value)}>{['Flood', 'Flash Flood', 'Heavy Rainfall', 'Landslide Risk', 'Strong Winds', 'Coastal Surge', 'Drought'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Source system *"><select value={selectedHazard.source} onChange={(e) => updateHazard('source', e.target.value)}>{[selectedHazard.source, 'River Gauge Network', 'Department of Meteorology', 'Field Report', 'NBRO Sensor Network', 'Local Authority Report'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Detected date *"><input type="date" defaultValue="2026-10-07" /></Field><Field label="Detected time *"><input type="time" defaultValue="09:15" /></Field><Field label="District *"><select value={selectedHazard.district} onChange={(e) => updateHazard('district', e.target.value)}>{['Colombo', 'Gampaha', 'Kandy', 'Galle', 'Matara', 'Ratnapura', 'Nuwara Eliya', 'Kalutara', 'Trincomalee', 'Batticaloa'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="DS division *"><select value={selectedHazard.ds} onChange={(e) => updateHazard('ds', e.target.value)}>{[selectedHazard.ds, 'Kelaniya', 'Wattala', 'Gampaha', 'Colombo', 'Kandy', 'Galle', 'Matara'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="GPS / location reference"><input value={selectedHazard.location} onChange={(e) => updateHazard('location', e.target.value)} /></Field><Field label="Confidence level *"><select value={selectedHazard.confidence} onChange={(e) => updateHazard('confidence', e.target.value)}>{['High', 'Medium', 'Low'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Severity *"><select value={selectedHazard.severity} onChange={(e) => updateHazard('severity', e.target.value)}>{['High', 'Medium', 'Low'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Current status *"><select value={selectedHazard.status} onChange={(e) => updateHazard('status', e.target.value)}>{['Monitoring', 'Active', 'Pending', 'Warning Issued'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Incident description / situation summary *" className="span-all"><textarea rows="5" maxLength="1000" value={selectedHazard.description} onChange={(e) => updateHazard('description', e.target.value)} /><small className="char-count">{selectedHazard.description.length} / 1000</small></Field></div></section>
      <section className="side-stack"><div className="panel location-card"><div className="panel-heading"><div><h2>Location preview</h2><p>{selectedHazard.district}, Sri Lanka</p></div></div><MapPanel compact pins={2}/></div><div className="panel form-panel"><div className="panel-heading"><div><h2>Evidence & supporting information</h2><p>Add verified context for this event</p></div></div><div className="mini-form"><Field label="Verified report count"><input type="number" min="0" value={reportCount} onChange={(e) => setReportCount(e.target.value)} /></Field><Field label="Photos attached"><input type="number" min="0" value={photoCount} onChange={(e) => setPhotoCount(e.target.value)} /></Field><Field label="Affected population estimate"><input value={selectedHazard.population} onChange={(e) => updateHazard('population', e.target.value)} /></Field><Field label="Infrastructure risk"><input defaultValue="Roads and low-lying homes" /></Field><Field label="Weather / field summary" className="span-all"><textarea rows="3" defaultValue="Local stations report sustained rainfall. Field teams are coordinating with district authorities." /></Field></div><button className="upload-box" onClick={() => setToast('File selection is ready when an upload service is connected')}><Download size={16}/> Attach report or photo <small>PDF, JPG or PNG · up to 10 MB</small></button></div></section></div>
    <div className="workflow-actions sticky-actions"><Button onClick={() => navigate('details', 'Hazard Monitoring')}>Cancel / back</Button><div><Button variant="secondary-blue" icon={Download} onClick={saveDraft}>Save draft</Button><Button variant="teal-button" icon={Check} onClick={() => { setToast('Hazard event updated'); }}>Update event</Button><Button variant="primary" icon={ArrowRight} onClick={() => navigate('level', 'Assessments')}>Continue to warning level</Button></div></div>
  </>;
}
