import { ArrowDown, ArrowLeft, ArrowRight, CheckCircle2, ChevronRight, Download, FileText, Image, MapPin, ShieldCheck } from 'lucide-react';

export default function DetailsScreen(props) {
  const { Header, Badge, Button, MapPanel, selectedHazard, navigate, setToast, reportCount, setReportCount, photoCount } = props;
  return <><div className="breadcrumbs"><button onClick={() => navigate('dashboard', 'Dashboard')}>Dashboard</button><ChevronRight size={14} /><button onClick={() => navigate('dashboard', 'Hazard Monitoring')}>Hazard monitoring</button><ChevronRight size={14} /><span>Hazard details</span></div><Header title="Hazard Details Review" eyebrow="HAZARD MONITORING · INCIDENT RECORD" actions={<Button icon={ArrowLeft} onClick={() => navigate('dashboard', 'Hazard Monitoring')}>Back to dashboard</Button>} />
    <div className="summary-band"><div><span>Hazard ID</span><strong>{selectedHazard.id}</strong></div><div><span>Hazard type</span><strong>{selectedHazard.type}</strong></div><div><span>District</span><strong>{selectedHazard.district}</strong></div><div><span>Severity</span><Badge>{selectedHazard.severity}</Badge></div><div><span>Status</span><Badge>{selectedHazard.status}</Badge></div></div>
    <div className="details-grid"><section className="panel detail-overview"><div className="panel-heading"><div><h2>Hazard overview</h2><p>Verified incident information</p></div><ShieldCheck className="panel-mark" size={21} /></div><dl className="detail-list"><div><dt>Hazard type</dt><dd>{selectedHazard.type}</dd></div><div><dt>Source</dt><dd>{selectedHazard.source}</dd></div><div><dt>First detected</dt><dd>07 Oct 2026, 09:15 AM</dd></div><div><dt>Last updated</dt><dd>07 Oct 2026, {selectedHazard.updated}</dd></div><div><dt>Severity</dt><dd><Badge>{selectedHazard.severity}</Badge></dd></div><div><dt>Confidence level</dt><dd>{selectedHazard.confidence} <span className="muted">· sensor and field reports</span></dd></div><div><dt>Affected district</dt><dd>{selectedHazard.district} <span className="muted">· {selectedHazard.ds} DS Division</span></dd></div><div><dt>Current status</dt><dd><Badge>{selectedHazard.status}</Badge></dd></div></dl><div className="description-box"><b>Situation summary</b><p>{selectedHazard.description}</p></div></section>
      <section className="panel details-map"><div className="panel-heading"><div><h2>Affected area map</h2><p>{selectedHazard.district} District, Sri Lanka</p></div><button className="icon-button" aria-label="Expand map" onClick={() => setToast('Map is already at its largest view')}><ArrowDown size={16} /></button></div><MapPanel /><div className="location-line"><MapPin size={15} /><span>{selectedHazard.location}</span><b>Population at risk: {selectedHazard.population}</b></div></section>
      <section className="panel timeline-panel"><div className="panel-heading"><div><h2>Incident timeline</h2><p>Latest events and updates</p></div></div><div className="timeline"><div><i className="timeline-dot blue"/><span>10:30 AM · 07 Oct 2026</span><p>Hazard review opened by Assessment Officer. Local authority has been notified.</p></div><div><i className="timeline-dot red"/><span>09:45 AM · 07 Oct 2026</span><p>{selectedHazard.description}</p></div><div><i className="timeline-dot amber"/><span>09:15 AM · 07 Oct 2026</span><p>Initial report received from {selectedHazard.source}.</p></div></div></section>
      <section className="panel evidence-panel"><div className="panel-heading"><div><h2>Evidence & reports</h2><p>Supporting information for assessment</p></div><Button icon={Download} onClick={() => setToast('Evidence summary downloaded')}>Export</Button></div><div className="evidence-counts"><div><FileText /><span><b>{reportCount}</b><small>Verified reports</small></span></div><div><Image /><span><b>{photoCount}</b><small>Photos received</small></span></div></div><div className="report-row"><span><CheckCircle2 size={16} /> Field assessment report</span><small>Verified · 09:42 AM</small></div><div className="report-row"><span><CheckCircle2 size={16} /> Weather station data</span><small>Verified · 09:33 AM</small></div><Button className="full-width" onClick={() => { setReportCount(String(Number(reportCount) + 1)); setToast('Related report added to this review') }}>View related reports</Button></section>
      <div className="workflow-actions"><Button onClick={() => navigate('dashboard', 'Hazard Monitoring')}>Back to dashboard</Button><Button variant="primary" icon={ArrowRight} onClick={() => navigate('assessment', 'Assessments')}>Proceed to assessment</Button></div></div>
  </>;
}
