import { Activity, ArrowRight, Check, Clock3, CloudRain, Download, FileText, Gauge, Info, Layers3, MapPin, Mountain, Users, Zap } from 'lucide-react';

export default function LevelScreen(props) {
  const { Header, Badge, Button, Field, selectedHazard, warning, navigate, updateWarning, saveDraft, setToast, evidenceRequested, setEvidenceRequested } = props;
  return <><Header title="Warning Level Selection" eyebrow="ASSESSMENT WORKFLOW · RISK EVALUATION" actions={<div className="updated"><Clock3 size={17}/><span><b>Review in progress</b><small>Assessment Officer</small></span></div>} /><div className="stepper"><div className="step done"><span><Check size={15}/></span>Review hazard</div><i/><div className="step done"><span><Check size={15}/></span>Assess event</div><i/><div className="step active"><span>3</span>Warning level</div><i/><div className="step"><span>4</span>Affected area</div><i/><div className="step"><span>5</span>Review</div></div><div className="summary-band compact-band"><div><span>Selected hazard</span><strong>{selectedHazard.id}</strong></div><div><span>Hazard type</span><strong>{selectedHazard.type}</strong></div><div><span>District</span><strong>{selectedHazard.district}</strong></div><div><span>Current status</span><Badge>{selectedHazard.status}</Badge></div></div>
    <div className="level-grid"><section className="panel factors-panel"><div className="panel-heading"><div><h2>Hazard factors</h2><p>Available assessment evidence</p></div><Info size={17}/></div>{[[FileText, 'Verified reports', '6 reports verified today'], [Activity, 'Sensor data', 'River levels rising · 3 active sensors'], [CloudRain, 'Weather forecast', 'Heavy rain expected for 6 hours'], [Mountain, 'Terrain risk', 'Moderate slope saturation'], [Users, 'Population exposure', `${selectedHazard.population} residents nearby`], [Layers3, 'Data sources', 'Meteorology, field teams, gauge network']].map(([Icon, title, detail]) => <div className="factor-row" key={title}><span className="factor-icon"><Icon size={19}/></span><b>{title}</b><span>{detail}</span></div>)}</section>
      <section className="panel level-form"><div className="panel-heading"><div><h2>Assessment</h2><p>Select the warning response</p></div></div><fieldset><legend>Select warning level</legend>{[['Low', 'Monitor conditions and issue a public advisory'], ['Medium', 'Prepare local response and inform at-risk communities'], ['High', 'Issue a public warning and prepare evacuation support'], ['Very High', 'Immediate protective action and emergency coordination']].map(([value, text]) => <label className={`level-option ${warning.level === value ? 'selected' : ''}`} key={value}><input type="radio" name="level" checked={warning.level === value} onChange={() => updateWarning('level', value)} /><span className={`level-marker ${value.toLowerCase()}`} /><b>{value}</b><small>{text}</small></label>)}</fieldset><div className="form-grid two-col"><Field label="Urgency"><select value={warning.urgency} onChange={(e) => updateWarning('urgency', e.target.value)}>{['Monitor', 'Within 6 hours', 'Immediate', 'Emergency'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Confidence level"><select value={warning.confidence} onChange={(e) => updateWarning('confidence', e.target.value)}>{['High', 'Medium', 'Low'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Response recommendation" className="span-all"><textarea rows="3" maxLength="500" value={warning.recommendation} onChange={(e) => updateWarning('recommendation', e.target.value)} /><small className="char-count">{warning.recommendation.length} / 500</small></Field></div><div className="risk-matrix"><b>Risk matrix <small>(impact × likelihood)</small></b><div className="matrix-layout"><span>Very high</span><i/><i/><i/><i className="risk-high"/><span>High</span><i/><i/><i className="risk-medium"/><i className="risk-high"/><span>Medium</span><i/><i className="risk-low"/><i className="risk-medium"/><i/><span>Low</span><i className="risk-low"/><i/><i/><i/></div><div className="matrix-x"><span>Low</span><span>Medium</span><span>High</span><span>Very high</span></div><div className="matrix-y">IMPACT</div><small className="likelihood-label">LIKELIHOOD →</small></div></section>
      <section className="panel recommendation-panel"><div className="panel-heading"><div><h2>Decision support</h2><p>System recommendation</p></div><Zap size={18}/></div><div className="recommended-box"><span className="stat-icon amber"><Gauge/></span><div><small>Recommended warning level</small><strong>{warning.level}</strong><span>Based on severity, exposure, and confidence</span></div></div><div className="recommend-stat"><Users/><div><small>Estimated affected population</small><b>{selectedHazard.population}</b></div></div><div className="recommend-stat"><MapPin/><div><small>Top affected areas</small><b>{selectedHazard.district}, Kelaniya, Wattala</b></div></div><Field label="Officer remarks"><textarea rows="4" maxLength="500" value={warning.remarks} onChange={(e) => updateWarning('remarks', e.target.value)} /><small className="char-count">{warning.remarks.length} / 500</small></Field></section></div>
    {evidenceRequested && <div className="evidence-hold"><Info size={16}/><span><b>Assessment paused.</b> Additional evidence has been requested. Continue the warning workflow after reports are reviewed.</span><Button onClick={() => { setEvidenceRequested(false); setToast('Evidence received and assessment resumed') }}>Resume assessment</Button></div>}
    <div className="workflow-actions"><Button onClick={() => navigate('assessment', 'Assessments')}>Back</Button><div><Button variant="secondary-blue" icon={Download} onClick={saveDraft}>Save draft</Button><Button variant="danger-button" icon={Users} onClick={() => { setEvidenceRequested(true); setToast('Evidence requested; warning progression paused'); }}>Request more evidence</Button><Button variant="primary" icon={ArrowRight} disabled={evidenceRequested} onClick={() => navigate('area', 'Assessments')}>Continue to affected area</Button></div></div>
  </>;
}
