import { Check, CheckCircle2, Clock3, CloudRain, Gauge, MapPin, MessageSquare, Send, Siren, Smartphone, Users } from 'lucide-react';

export default function ReviewScreen(props) {
  const { Header, Button, selectedHazard, warning, navigate, updateWarning, setModal, toggleCheck, checks } = props;
  return <><Header title="Review, Confirm & Publish Warning" eyebrow="FINAL CHECK · PUBLIC SAFETY MESSAGE" /><div className="stepper"><div className="step done"><span><Check size={15}/></span>Review hazard</div><i/><div className="step done"><span><Check size={15}/></span>Assess event</div><i/><div className="step done"><span><Check size={15}/></span>Warning level</div><i/><div className="step done"><span><Check size={15}/></span>Affected area</div><i/><div className="step active"><span>5</span>Review & publish</div></div>
    <div className="summary-tiles"><div><span className="tile-icon teal"><CloudRain/></span><small>Hazard</small><b>{selectedHazard.id} · {selectedHazard.type}</b></div><div><span className="tile-icon amber"><Gauge/></span><small>Warning level</small><b>{warning.level}</b></div><div><span className="tile-icon blue"><MapPin/></span><small>Affected areas</small><b>{warning.areas.length} locations</b></div><div><span className="tile-icon slate"><Users/></span><small>Estimated target</small><b>{(warning.areas.length * 12480).toLocaleString()} citizens</b></div></div>
    <div className="review-grid"><section className="panel review-channels"><div className="panel-heading"><div><h2>Selected channels</h2><p>Delivery methods for this warning</p></div></div>{warning.channels.map((channel) => <div className="review-channel" key={channel}><span className="factor-icon">{channel === 'SMS Alert' ? <MessageSquare/> : channel === 'Audible / Siren' ? <Siren/> : <Smartphone/>}</span><b>{channel}</b><CheckCircle2 size={17}/></div>)}</section><section className="panel preview-panel"><div className="panel-heading"><div><h2>Message preview</h2><p>{warning.language} · {warning.format}</p></div></div><div className="preview-card"><div className="preview-top"><span className="level-marker high"/><b>{warning.title}</b></div><p>{warning.message}</p><div className="preview-instructions"><b>What you should do</b><p>{warning.instructions}</p></div><small><MapPin size={14}/> {warning.areas.join(', ')}</small></div></section><section className="panel validity-panel"><div className="panel-heading"><div><h2>Validity period</h2><p>Warning schedule</p></div></div><div className="validity-row"><span>From</span><b>{new Date(warning.start).toLocaleString()}</b></div><div className="validity-row"><span>To</span><b>{new Date(warning.end).toLocaleString()}</b></div><div className="validity-row"><span>Auto-expiry</span><b>{new Date(warning.expiry).toLocaleString()}</b></div><div className="validity-summary"><Clock3/><span><small>Duration</small><b>24 hours</b></span></div></section><section className="panel checklist-panel"><div className="panel-heading"><div><h2>Confirmation checklist</h2><p>Confirm each item before publication</p></div></div>{['Hazard verified', 'Affected area confirmed', 'Message reviewed', 'Channels selected'].map((label, index) => <label key={label}><input type="checkbox" checked={checks[index]} onChange={() => toggleCheck(index)}/><span>{checks[index] ? <Check size={13}/> : null}</span>{label}</label>)}</section><section className="panel officer-remarks"><div className="panel-heading"><div><h2>Officer remarks</h2><p>Optional internal note</p></div></div><textarea rows="5" maxLength="500" value={warning.remarks} onChange={(e) => updateWarning('remarks', e.target.value)} /><small className="char-count">{warning.remarks.length} / 500 characters</small></section></div>
    <div className="workflow-actions"><Button onClick={() => navigate('area', 'Assessments')}>Back to edit</Button><div><Button variant="secondary" onClick={() => setModal('cancel-process')}>Cancel process</Button><Button variant="primary" icon={Send} disabled={!checks.every(Boolean)} onClick={() => setModal('publish')}>Publish warning</Button></div></div>
  </>;
}
