const router = require('express').Router();
const { rateLimit } = require('express-rate-limit');
const controller = require('./auth.controller');
const requireAuth = require('../../middleware/auth');
const limiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 20, skipSuccessfulRequests: true, standardHeaders: 'draft-8', legacyHeaders: false, message: { success: false, message: 'Too many attempts. Please try again in 15 minutes.' } });
router.post('/register', limiter, controller.register);
router.post('/login', limiter, controller.login);
router.get('/me', requireAuth, controller.me);
router.post('/logout', requireAuth, controller.logout);
module.exports = router;
