import { useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { Icon } from './UI';
export function Brand({ large = false }) {
  return <View style={a.brand}><View style={[a.mark, large && a.largeMark]}><Icon name="shield-checkmark-outline" size={large ? 64 : 30} color="#135E42" /></View><Text style={[a.brandName, large && { fontSize: 28 }]}>ResQConnect</Text></View>;
}
export function AuthLayout({ children, title, subtitle }) {
  return <LinearGradient colors={['#CEE8D1', '#EDF2EF']} style={a.flex}><SafeAreaView style={a.flex}><KeyboardAvoidingView style={a.flex} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={a.page}><Brand /><View style={a.heading}><Text style={a.title}>{title}</Text><Text style={a.subtitle}>{subtitle}</Text></View>{children}</ScrollView></KeyboardAvoidingView></SafeAreaView></LinearGradient>;
}
export function AuthInput({ label, icon, value, onChangeText, error, password = false, disabled = false, ...props }) {
  const [visible, setVisible] = useState(false);
  return <View style={a.field}><Text style={a.label}>{label}</Text><View style={[a.inputRow, error && { borderColor: '#BA5B51' }]}><Icon name={icon} size={20} color="#7A9184" /><TextInput accessibilityLabel={label} editable={!disabled} value={value} onChangeText={onChangeText} secureTextEntry={password && !visible} placeholderTextColor="#83938A" style={a.input} {...props} />{password && <Pressable accessibilityRole="button" accessibilityLabel={visible ? 'Hide password' : 'Show password'} onPress={() => setVisible(current => !current)} style={a.eye}><Icon name={visible ? 'eye-off-outline' : 'eye-outline'} size={20} color="#7A9184" /></Pressable>}</View>{error && <Text accessibilityLiveRegion="polite" style={a.error}>{error}</Text>}</View>;
}
export function AuthButton({ title, onPress, busy = false, secondary = false }) {
  return <Pressable accessibilityRole="button" accessibilityState={{ disabled: busy, busy }} disabled={busy} onPress={onPress} style={({ pressed }) => [a.button, secondary && a.secondary, (pressed || busy) && { opacity: 0.65 }]}>{busy ? <ActivityIndicator color="white" /> : <><Text style={[a.buttonText, secondary && { color: '#17644D' }]}>{title}</Text><Icon name="arrow-forward" size={20} color={secondary ? '#17644D' : 'white'} /></>}</Pressable>;
}
export const a = StyleSheet.create({ flex: { flex: 1 }, page: { padding: 24, paddingTop: 30, paddingBottom: 35, flexGrow: 1, maxWidth: 560, width: '100%', alignSelf: 'center', gap: 18 }, brand: { alignItems: 'center', gap: 12 }, mark: { width: 64, height: 64, borderRadius: 20, backgroundColor: '#E6F2E8', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#F7FFF8' }, largeMark: { width: 124, height: 124, borderRadius: 36 }, brandName: { fontSize: 19, color: '#143F2C', fontWeight: '800' }, heading: { marginTop: 18, marginBottom: 5, gap: 8 }, title: { fontSize: 30, lineHeight: 38, color: '#113724', fontWeight: '800', letterSpacing: -0.8 }, subtitle: { fontSize: 15, lineHeight: 23, color: '#607568' }, card: { padding: 20, borderRadius: 22, backgroundColor: '#FCFEFC', borderWidth: 1, borderColor: '#E1ECE4', gap: 17 }, field: { gap: 8 }, label: { color: '#254E37', fontSize: 13, fontWeight: '700' }, inputRow: { minHeight: 54, flexDirection: 'row', alignItems: 'center', borderColor: '#DFE9E1', borderWidth: 1, backgroundColor: '#F7FAF7', paddingLeft: 13, borderRadius: 13, gap: 10 }, input: { flex: 1, minHeight: 52, fontSize: 15, color: '#203C2C', paddingVertical: 12, paddingRight: 10 }, roleOptions: { gap: 8 }, roleOption: { minHeight: 60, flexDirection: 'row', alignItems: 'center', gap: 11, padding: 11, borderWidth: 1, borderColor: '#DFE9E1', borderRadius: 12, backgroundColor: '#F7FAF7' }, roleOptionSelected: { borderColor: '#238160', backgroundColor: '#EAF5EF' }, roleRadio: { width: 17, height: 17, borderRadius: 9, borderWidth: 2, borderColor: '#8CA096' }, roleRadioSelected: { borderColor: '#167153', backgroundColor: '#167153', shadowColor: '#fff', shadowRadius: 2, shadowOpacity: 1 }, roleCopy: { flex: 1 }, roleTitle: { color: '#254E37', fontSize: 13, fontWeight: '700' }, roleDescription: { marginTop: 2, color: '#6D8176', fontSize: 11, lineHeight: 16 }, eye: { width: 44, height: 50, alignItems: 'center', justifyContent: 'center' }, button: { minHeight: 55, borderRadius: 14, backgroundColor: '#09603F', padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 }, buttonText: { fontSize: 16, fontWeight: '700', color: 'white' }, secondary: { backgroundColor: '#E3EFE5', borderWidth: 1, borderColor: '#BED4C4' }, error: { color: '#AF443F', fontSize: 13, lineHeight: 20 }, message: { padding: 12, backgroundColor: '#E8F2E9', borderRadius: 12 }, messageText: { color: '#2F6A47', fontSize: 13, lineHeight: 20 }, switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', flexWrap: 'wrap', gap: 5 }, switchText: { color: '#627A6B', fontSize: 14 }, link: { color: '#09603F', fontWeight: '700', fontSize: 14 }, touch: { minHeight: 44, justifyContent: 'center' }, footer: { fontSize: 12, color: '#748B7B', textAlign: 'center', lineHeight: 19 } });
