import { useCallback, useState } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { Text, View } from 'react-native';
import { Button, Card, EmptyState, LoadingState, Notice, Screen, SectionTitle, ui } from '../components/UI';
import { loadOperationalUpdates } from '../services/operationalUpdates';

const readable = value => String(value || 'Not available').replaceAll('_', ' ');
const StatusBadge = ({ status }) => <Text style={ui.cardTitle}>{readable(status)}</Text>;
export default function StaffUpdatesScreen({ activityOnly = false }) {
  const [state, setState] = useState({ loading: true, error: '', requests: [], incidents: [], distributions: [] });
  const load = useCallback(async () => { setState(current => ({ ...current, loading: true, error: '' })); try { setState({ loading: false, error: '', ...await loadOperationalUpdates() }); } catch (error) { setState(current => ({ ...current, loading: false, error: error.response?.data?.error?.message || 'Unable to load operational updates.' })); } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const visible = activityOnly ? state.requests.filter(request => ['APPROVED', 'REJECTED', 'DISPATCHED'].includes(request.status)) : state.requests;
  return <Screen title={activityOnly ? 'Operational Activity' : 'Staff Operations'} subtitle="Read-only updates from Response and District Coordination.">{state.error && <><Notice warning>{state.error}</Notice><Button title="Retry" secondary onPress={load}/></>}{state.loading ? <LoadingState message="Loading operational updates…"/> : <><View style={ui.row}><Card style={ui.flex}><Text style={ui.overline}>ACTIVE INCIDENTS</Text><Text style={ui.title}>{state.incidents.length}</Text></Card><Card style={ui.flex}><Text style={ui.overline}>EN ROUTE</Text><Text style={ui.title}>{state.distributions.filter(item => item.status === 'EN_ROUTE').length}</Text></Card></View><SectionTitle title={activityOnly ? 'Approval and dispatch activity' : 'Response request notifications'}/>{visible.length === 0 ? <EmptyState title="No operational updates" message="New requests and dispatch activity will appear here from backend data."/> : visible.map(request => <Card key={request.id}><View style={ui.sectionRow}><View style={ui.flex}><Text style={ui.overline}>{request.status === 'PENDING' ? 'NEW RESPONSE REQUEST' : request.status === 'DISPATCHED' ? 'TEAM DISPATCHED' : 'REQUEST UPDATE'}</Text><Text style={ui.cardTitle}>{readable(request.capability)}</Text></View><StatusBadge status={request.status}/></View><Text>Incident: <Text style={ui.cardTitle}>{request.incident?.incidentId}</Text></Text><Text style={ui.muted}>{request.requestedPersonnelCount} personnel · {request.requestedLocation}</Text><Text style={ui.muted}>Required: {new Date(request.requiredAt).toLocaleString()} · {request.priority}</Text>{request.approvedTeam && <Text>Team: <Text style={ui.cardTitle}>{request.approvedTeam.name}</Text></Text>}{request.rejectionReason && <Notice warning>{request.rejectionReason}</Notice>}</Card>)}<SectionTitle title="Relief delivery updates"/>{state.distributions.length === 0 ? <Text style={ui.muted}>No distributions recorded for active incidents.</Text> : state.distributions.map(item => <Card key={item.id}><View style={ui.sectionRow}><View style={ui.flex}><Text style={ui.overline}>{item.incidentId}</Text><Text style={ui.cardTitle}>{item.item?.itemName || item.distributionId}</Text></View><StatusBadge status={item.status}/></View><Text style={ui.muted}>{item.quantity} {item.item?.unit || ''} · {item.shelter?.name || 'Shelter unavailable'}</Text></Card>)}</>}</Screen>;
}
